name: Update CVE Data

on:
  schedule:
    - cron: '*/10 * * * *'  # 每10分钟运行一次
  workflow_dispatch:

jobs:
  update-cves:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # 使用 Python 3.11
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-dev libxslt1-dev python3-dev
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # 先安装预编译的 lxml
          pip install --only-binary :all: lxml==4.9.3
          # 安装其他依赖
          pip install -r requirements.txt
          
      - name: Update CVE data
        env:
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
        run: |
          mkdir -p logs
          python scripts/update_cves.py
        
      - name: Commit and push if changed
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add data/ logs/
          git commit -m "Update CVE data and logs" || exit 0
          git push 